### ISSUE TITLE
Not sure if Turbolinks acting up (see attached)

### ISSUE THREAD

**Issue by djrobby** [janko/rodauth-demo-rails#4]
Hi Janko,

First of all, thank you so much for your contribution. I'm merely acting as a test user for your project in hopes to finally find a viable replacement for bloated Devise!

I am not sure if Turbolinks is responsible for the issue below. Basically, once a user **confirms** their account, the **flash message** continues to tell them they are not yet verified.
 
![20200405-001](https://user-images.githubusercontent.com/22199/81927502-bbc19f00-95b1-11ea-9a64-156db892216e.gif)

**Comment by janko** [comment]
Thanks for the report and explanatory GIF!

Notice that the message before the change login page is different after you've verified the account. After verification it's just asking you to confirm your *password*, just like the change password page is asking you.

Note that this is not default Rodauth behaviour, it's just to show an example of a separate password confirmation dialog. You could remove these lines: https://github.com/janko/rodauth-demo-rails/blob/7463fd36173e785bdd348a1d4e9e5bc8703a8b08/lib/rodauth_app.rb#L77-L80

and you'll get sent directly to change password/login pages, which will then ask for the current password as part of the form.

**Comment by djrobby** [comment]
Got it! Thank you for the explanation.
