### ISSUE TITLE
Password Reset Link

### ISSUE THREAD

**Issue by djrobby** [janko/rodauth-demo-rails#5]
https://github.com/janko/rodauth-demo-rails/blob/7463fd36173e785bdd348a1d4e9e5bc8703a8b08/lib/rodauth_app.rb#L42

should be...

```ruby
RodauthMailer.reset_password(email_to, reset_password_email_link).deliver_later
```

**Comment by janko** [comment]
Good catch, I've missed that one. Fixed now as well ✅
