### ISSUE TITLE
reset-password page not showing?

### ISSUE THREAD

**Issue by benkoshy** [janko/rodauth-demo-rails#9]
@janko thank you for your work.

- perhaps consider opening up the discussion board on this repo. 
- I'm likely doing something crazy. it it takes longer than 2 minutes to solve - don't worry about it -- i can always come back to this.

### Steps to Reproduce

1. Clone the repository, run the migrations.
2. Create a user account, or register a user. Login.
3. Visit this path:  http://localhost:3000/reset-password
4. The page is empty. Is this the expected behaviour?
5. The only thing I could think of was that the `reset-password` route is a post / put request. But there is a "reset-password" template generated

![image](https://user-images.githubusercontent.com/15097447/171556316-e19c72b9-1bbf-4aa9-83a9-1b1184b5719e.png)

![image](https://user-images.githubusercontent.com/15097447/171556474-9e3bb1fa-cff4-4093-8f5a-f67dddede13b.png)

```sh
Started GET "/reset-password" for 127.0.0.1 at 2022-06-02 14:59:48 +1000
Processing by RodauthApp#call as HTML
Completed 404 Not Found in 1ms (ActiveRecord: 0.0ms | Allocations: 98)

Started GET "/reset-password" for 127.0.0.1 at 2022-06-02 15:01:31 +1000
Processing by RodauthApp#call as HTML
Completed 404 Not Found in 0ms (ActiveRecord: 0.0ms | Allocations: 86)
```

**Comment by janko** [comment]
The `/reset-password-request` page is the one where you request a password reset, `/reset-password` is the page linked in the email, which requires the single-use token in the URL param. You'll notice the login page links to the `/reset-password-request` page.

> perhaps consider opening up the discussion board on this repo.

OK, that's reasonable, I enabled it now.

**Comment by benkoshy** [comment]
I'll post a PR to update the rake routes task where this will be made manifest.
